### ISSUE TITLE
Argo Rollout extension functionality is not seeing in the dashboard

### ISSUE THREAD

**Issue by sree-warrier** [argoproj-labs/rollout-extension#3]
Followup with the issue which was closed. 

https://github.com/argoproj-labs/rollout-extension/issues/1

We have tried to configure the Argo rollout extension with version 2.1.5, but still we are unable to see the UI feature for rollouts.

**Comment by guillomep** [comment]
I have the same problems with the version 2.1.7

**Comment by sree-warrier** [comment]
Guys any update or suggestion on this

**Comment by DanOfir** [comment]
also not working for me, installed on argocd version 2.2.3
this is what is see in logs:

ERROR   controller.argocdextension      Reconciler error        {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argo-rollouts", "namespace": "argocd", "error": "remove /tmp/extensions/.argo-rollouts.snapshot: no such file or directory"}

**Comment by royeectu** [comment]
I'm getting the following error with Argo CD: v2.2.5+8f981cc

```
2022-02-15T17:54:24.100Z        ERROR   controller.argocdextension      Reconciler error        {"reconciler group": "argoproj.io", "reconciler kind": "ArgoCDExtension", "name": "argo-rollouts", "namespace": "royeet", "error": "remove /tmp/extensions/.argo-rollouts.snapshot: no such file or directory"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.10.1/pkg/internal/controller/controller.go:227
```

**Comment by yq314** [comment]
For me, I noticed that one of my CRD (ArgoCDExtension) has a `deletionTimestamp` in its metadata which means it's trying to delete it and blocked by the finalizer. Probably because I was playing with my installation and initialised a deletion some time earlier.

These steps helped me to resolve the issue:
- remove the finalizer from the CRD, it will then be deleted automatically
- create the CRD manually
- restart the argocd-server pod (including the extension container)

**Comment by renilthomas** [comment]
Does it work with v2.2.5 argocd? Everything loaded fine but cannot see the UI.

**Comment by alexef** [comment]
thank you @yq314

**Comment by pc-tzimmerman** [comment]
I just set this up today and thought it was pretty straightforward. Thought I would post my process here for posterity. 

I use the ArgoCD Helm Chart to install ArgoCD presently. To use Argo Rollouts, you need to enable the Extensions controller for ArgoCD. This effectively runs as a second container within the Server pod. To accomplish this, add the following to the `server` section of your CD values.yaml file. 

```yaml
server:
  extensions:
    enabled: true
```

After this, you need to deploy Argo Rollouts. I also use Helm for this. Rollouts' Helm Chart supports an `extraObjects` field in the values.yaml file. To which you should add the following:

```yaml
        extraObjects:
          - apiVersion: argoproj.io/v1alpha1
            kind: ArgoCDExtension
            metadata:
              name: argo-rollouts
              finalizers:
                - extensions-finalizer.argocd.argoproj.io
            spec:
              sources:
              - web:
                  url: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.1.0/extension.tar
```

This isn't necessary. You could, of course, just deploy this manifest to your cluster after deploying Rollouts. However, make sure you add a `namespace: argocd-system` or whatever to the metadata. Argo Server will only detect the CRD if it is in the same namespace.

To validate that this is working, you can check the contents of `/tmp/extensions/` in the new argo-extensions container. Something like this:

```
$> kubectl exec -it -n argo-system argocd-server-7f56db796f-mj8d9 -c argocd-extensions -- ls /tmp/extensions/resources/argoproj.io/Rollout/ui
1.extensions.js  extensions.js
```
