### ISSUE TITLE
Something went wrong with Extension for Rollout

### ISSUE THREAD

**Issue by beejiujitsu** [argoproj-labs/rollout-extension#33]
Re: https://github.com/argoproj-labs/rollout-extension/issues/30

I am also having the same problem:

<img width="1198" alt="Screenshot 2022-12-03 at 3 40 03 PM" src="https://user-images.githubusercontent.com/4237425/205501951-9049aa28-ad48-4ad3-93f6-e29306a93608.png">

ArgoCD details:

```
{
    "Version": "v2.5.3+0c7de21",
    "BuildDate": "2022-11-28T16:51:33Z",
    "GitCommit": "0c7de210ae66bf631cc4f27ee1b5cdc0d04c1c96",
    "GitTreeState": "clean",
    "GoVersion": "go1.18.8",
    "Compiler": "gc",
    "Platform": "linux/amd64",
    "KustomizeVersion": "v4.5.7 2022-08-02T16:35:54Z",
    "HelmVersion": "v3.10.1+g9f88ccb",
    "KubectlVersion": "v0.24.2",
    "JsonnetVersion": "v0.18.0"
}
```

ArgoCDExtension argo-rollouts manifest: 

```
apiVersion: argoproj.io/v1alpha1
kind: ArgoCDExtension
metadata:
  finalizers:
    - extensions-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/instance: argocd-int
  name: argo-rollouts
  namespace: argocd
spec:
  sources:
    - web:
        url: >-
          https://github.com/argoproj-labs/rollout-extension/releases/download/v0.2.1/extension.tar
```

Argo rollouts is kustomized and applied as a base with no modifications from https://github.com/argoproj/argo-rollouts//manifests/cluster-install?version=v1.3.1

The Rollout manifest is quite minimal for canary config:

```
  strategy:
    canary:
      maxSurge: 100%
      maxUnavailable: 25%
```

Full manifest with REDACTED details:

```
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations: {}
  labels:
    app: REDACTED
    app.kubernetes.io/instance: REDACTED
  name: REDACTED
  namespace: int
spec:
  replicas: 5
  selector:
    matchLabels:
      app: REDACTED
  strategy:
    canary:
      maxSurge: 100%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: REDACTED
    spec:
      containers:
        - env: [...]
          image: 'REDACTED'
          name: REDACTED
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 3000
          resources:
            limits:
              cpu: '1'
              memory: 512Mi
            requests:
              cpu: 500m
              memory: 200Mi
        - command:
            - /cloud_sql_proxy
            - '-ip_address_types=PRIVATE'
            - '-log_debug_stdout'
            - >-
              -instances=REDACTED
            - '-structured_logs'
            - '-use_http_health_check'
          image: 'gcr.io/cloudsql-docker/gce-proxy:1.33.1'
          name: cloud-sql-proxy
          resources:
            requests:
              cpu: '1'
              memory: 2Gi
          securityContext:
            runAsNonRoot: true
      initContainers: []
      serviceAccountName: cloud-sql-proxy
      terminationGracePeriodSeconds: 30
```
