### ISSUE TITLE
No container or image tag shown on the dashboard

### ISSUE THREAD

**Issue by beyondbill** [argoproj-labs/rollout-extension#56]
What ArgoCD dashboard shows
<img width="826" alt="Screenshot 2023-09-11 at 2 29 25 PM" src="https://github.com/argoproj-labs/rollout-extension/assets/10553863/bb1269b0-5357-4a0d-aad1-23812578d1eb">

The same Rollout in Argo Rollouts Dashboard
<img width="952" alt="image" src="https://github.com/argoproj-labs/rollout-extension/assets/10553863/88db7771-d667-49e9-b314-244f9ee7cc2c">

The Rollout's template
```yaml
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  annotations:
    rollout.argoproj.io/revision: "586"
    rollout.argoproj.io/workload-generation: "724"
  creationTimestamp: "2023-06-28T16:30:09Z"
  labels:
    argocd.argoproj.io/instance: orchestrator-69ff9
  name: orchestrator
  namespace: orchestrator
spec:
  replicas: 2
  strategy:
    canary:
      analysis:
        args:
        - name: appName
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: k8sCluster
          value: gcp/frontend-staging-1-us-central1
        - name: k8sNamespace
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: canaryPodHash
          valueFrom:
            podTemplateHashValue: Latest
        templates:
        - clusterScope: true
          templateName: error-rate
        - clusterScope: true
          templateName: latency-average
        - clusterScope: true
          templateName: cpu-utilization
        - clusterScope: true
          templateName: memory-utilization
      canaryService: orchestrator-canary
      stableService: orchestrator
      steps:
      - setWeight: 20
      - pause:
          duration: 10m
      - setWeight: 50
      - pause:
          duration: 5m
      trafficRouting:
        nginx:
          stableIngress: orchestrator-ingress
  workloadRef:
    apiVersion: apps/v1
    kind: Deployment
    name: orchestrator
```

ArgoCD version is v2.5.5
Argo Rollouts version is v1.4.0
Rollout-extension version is v0.3.1
Kubernetes version is v1.24.14

I don't think this is a permission issue as the SA used by ArgoCD server has been bind to a k8s clusterrole with full permissions

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argocd-manager-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
```
