### ISSUE TITLE
Update since argocd-extensions is deprecated

### ISSUE THREAD

**Issue by otherguy** [argoproj-labs/rollout-extension#62]
Now that `argocd-extensions` is [deprecated](https://github.com/argoproj-labs/argocd-extensions?tab=readme-ov-file#deprecation-notice), will this repo be updated for the new way of defining extensions?

**Comment by abhishekpolavarapu** [comment]
I dont think, any update is required for this to use with new argocd-extensions-installer
If you are using argocd helm you can use this extension by configuring argocd like below:
```yaml
   server:
    initContainers:
      - name: extension-rollouts
        image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
        env:
        - name: HTTPS_PROXY
          value: http://proxy.config.pcp.local:3128
        - name: EXTENSION_URL
          value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
        volumeMounts:
          - name: extensions
            mountPath: /tmp/extensions/
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
    volumeMounts:
    - name: extensions
      mountPath: /tmp/extensions/
    volumes:
    - name: extensions
      emptyDir: {}
```
