### ISSUE TITLE
Provide checksum accessible by URL

### ISSUE THREAD

**Issue by jcogilvie** [argoproj-labs/rollout-extension#67]
The new argo extension mechanism would prefer to have a checksum to validate the integrity of the downloaded extension like so:

```yaml
  initContainers:
    - name: rollout-extension
      image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
      env:
        - name: EXTENSION_URL
          value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.3/extension.tar
#        - name: EXTENSION_CHECKSUM_URL
#          value: TODO
```
