### ISSUE TITLE
argocd-extension-installer is deployed but "more" tab is missing.

### ISSUE THREAD

**Issue by rajgupta2720** [argoproj-labs/rollout-extension#80]
Argo rollouts version: 1.7.1 (Installed in argo-rollouts namespace).
ArgoCD version: 2.11.5  (Installed in argocd namespace via helm chart)

`extensions:
    enabled: true
    image:
      repository: "quay.io/argoprojlabs/argocd-extension-installer"
      tag: "v0.0.5"
      imagePullPolicy: ""
    extensionList:
      - name: rollout-extension
        env:
          - name: EXTENSION_URL
            value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.5/extension.tar`

![image](https://github.com/user-attachments/assets/37fbc579-9e64-428a-b4ef-2b6516efd0dc)

I could see init-container is completed successfully. However, I can't see extension or "more" tab in ArgoCD UI or is there any other way to verify? Not sure what am I missing.

**Comment by drtinkerer** [comment]
did you manage to sort this ?

**Comment by nicl-dev** [comment]
We do have the same problem. Init container completed succesfully but there is no `More` Tab or similar on our Rollout ressources. Is there a recommended way to debug this or see the installed extensions in ArgoCD?

**Comment by Gowtham029** [comment]
@rajgupta2720, do you have any solution for this?

I have the same issues.

Argo rollouts version: 1.7.2 (Installed in argo-rollouts namespace).
ArgoCD version: v2.12.6+4dab5bd  (Installed in good namespace via helm chart)

When I tried to view the created pod manifest, I got this.

```YAML
initContainers:
  - env:
    - name: EXTENSION_URL
      value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar
    image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.5
    imagePullPolicy: IfNotPresent
    name: rollout-extension
    resources: {}
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /tmp/extensions/
      name: extensions
    - mountPath: /tmp
      name: tmp
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-7cv7r
      readOnly: true

```
