### ISSUE TITLE
How to disable/remove the rollout plugin?

### ISSUE THREAD

**Issue by saumeya** [argoproj-labs/rollout-extension#85]
I was able to add the plugin to ArgoCD by adding the initContainers, volumes and volumeMounts as mentioned in the README, but removing these fileds from the server deployments doesn't remove the plugin from the UI. How to disable? 

```
server:
  initContainers:
    - name: rollout-extension
      image: quay.io/argoprojlabs/argocd-extension-installer:v0.0.1
      env:
      - name: EXTENSION_URL
        value: https://github.com/argoproj-labs/rollout-extension/releases/download/v0.3.4/extension.tar
      volumeMounts:
        - name: extensions
          mountPath: /tmp/extensions/
      securityContext:
        runAsUser: 1000
        allowPrivilegeEscalation: false
  volumeMounts:
    - name: extensions
      mountPath: /tmp/extensions/
  volumes:
    - name: extensions
      emptyDir: {} 
```
